# PostgreSQL

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: fediverse
  labels:
    app: postgres
    fediverse/role: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: fediverse-database

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: fediverse
  labels:
    app: postgres
    fediverse/role: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:11.2-alpine
          livenessProbe:
            exec:
              command: [/bin/sh, -c, pg_isready -U postgres]
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
            requests:
              memory: 70Mi
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: fediverse
  labels:
    app: postgres
    fediverse/role: database
spec:
  clusterIP: None
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
