# https://github.com/kubernetes-incubator/external-storage/blob/nfs-provisioner-v2.2.1-k8s1.12/nfs/deploy/kubernetes/deployment.yaml
# 変更点
# * namespace を fediverse に
# * fediverse/nfs=true のノードにデプロイするようにした
# * コンテナのバージョンを v2.2.1-k8s1.12 に固定
# * provisioner を fediverse.cluster.local/nfs に
# * resources を設定

apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-provisioner
  namespace: fediverse
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-provisioner
  namespace: fediverse
  labels:
    app: nfs-provisioner
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
    - name: rpcbind-udp
      port: 111
      protocol: UDP
  selector:
    app: nfs-provisioner
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-provisioner
  namespace: fediverse
spec:
  selector:
    matchLabels:
      app: nfs-provisioner
  replicas: 1
  strategy:
    type: Recreate 
  template:
    metadata:
      labels:
        app: nfs-provisioner
    spec:
      serviceAccount: nfs-provisioner
      containers:
        - name: nfs-provisioner
          image: quay.io/kubernetes_incubator/nfs-provisioner:v2.2.1-k8s1.12
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
            - name: rpcbind-udp
              containerPort: 111
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - DAC_READ_SEARCH
                - SYS_RESOURCE
          args:
            - "-provisioner=fediverse.cluster.local/nfs"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_NAME
              value: nfs-provisioner
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              memory: 300Mi
            requests:
              memory: 140Mi
          volumeMounts:
            - name: export-volume
              mountPath: /export
      nodeSelector:
        fediverse/nfs: "true"
      volumes:
        - name: export-volume
          hostPath:
            path: /var/local/fediverse/nfs
            type: DirectoryOrCreate
